--- # Delegation Example Async
- hosts: webservers
  tasks:
        - name: Run sleep.sh
          command: /home/ansible/sleep.sh
          async: 60
          poll: 0
          delegate_to: node1
        
        - name: Install mariadb
          package:
                  name: mariadb
                  state: latest
          become: yes

